Adapt flows to previous changes
bifurcation/ietf-mimi-protocol pull request #10
Opened 2023-11-02 11:07 UTC by kkohbrok

2023-11-02 15:41 UTC, rohan-wire requested changes

2023-11-02 15:41 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +> Welcome.
This is the opposite of the normal flow in most messengers. We need an Add flow and it should be first.

2023-11-02 15:41 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +> **TODO**: We probably won't need this event, as `ds.fetch_group_info` contains
Just delete the section please

2023-11-02 23:51 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +> Welcome.
The user visible behavior is that Alice adds Bob and immediately sends a message. The expectation in most messengers is that Bob's clients can view the message that Alice just sent.

2023-11-03 10:07 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +> Welcome.
I think there are two distinct flows here that I think we should cover.

1. The "invite" flow, where Alice invites Bob and Bob only becomes part of the room once he has accepted the invitation, and
2. the "add" flow, where Alice adds Bob and Bob immediately becomes a part of the room without any additional involvement by Bob.

Flow 1 would be based on external commit and corresponds, for example, to Signal's flow with invite links. Flow 2 is the flow you allude to, based on Welcome, and is based on Signal's flow, where once Alice has a connection with Bob, she can add him to other groups without Bob's involvement.

2023-11-03 10:12 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +> Welcome.
The issue I see with the "Add" flow is that we probably want to add some degree of consent signaling, s.t. the Hub and other participants can verify that Alice has Bob's permission to Add Bob to the room.

2023-11-03 19:43 UTC, rohanmahy approved these changes

2023-11-03 19:44 UTC, rohanmahy commented on draft-ralston-mimi-protocol.md
> +> Welcome.
looks good

2023-11-03 21:02 UTC, rohan-wire approved these changes

2023-11-03 21:03 UTC, merged