Remove extraneous m. in front of room events
bifurcation/ietf-mimi-protocol pull request #20
Opened 2023-11-06 15:09 UTC by rohan-wire

globally replace `m.room.` with `room.` in event names.

2023-11-06 19:54 UTC, turt2live requested changes
see threaded comment

2023-11-06 19:54 UTC, turt2live commented on draft-ralston-mimi-protocol.md
The prefix exists to ensure namespacing is possible, as folks may want to add their own event types to the protocol. For example, to accomplish DoubleRatchet use cases. 

It was my intention to also prefix the DS events with `m.` for consistency and building the official namespace. The namespace needs to be codified in the IANA registry still, but that was largely assumed to be a later problem.

`m.` is shorthand for `mimi.`, which we can expand if needed.

2023-11-06 20:12 UTC, bifurcation commented
Yeah, I'm inclined to leave this for the WG to comment on.  The traditional IETF approach to something like this would be to have an IANA registry where certain values are registered (those that would be `m.` here) and certain values would be vendor space (I believe the Matrix pattern for these is `com.example.foo`).  If we were talking about numerical code points, the analogy would be exact, since if you know the range of numbers reserved for vendor usage (≈ non-`m.` here), you can look at a value and tell if it's registered or vendor.

For text-like registries, things are a little less clear.  Traditionally, these registries don't have an explicit vendor reservation, since space is not constrained.  (See, e.g., the [ACME directory metadata fields registry](https://www.iana.org/assignments/acme/acme.xhtml#acme-directory-metadata-fields).)  If you want a value for some proprietary thing, you just choose one and use it, and if some official thing later collides with it, oh well.  And in cases where there were explicit affordances for experimental (e.g., `X-` and `P-` in HTTP/SIP headers), those affordances [are now deprecated](https://datatracker.ietf.org/doc/html/rfc6648).

So it's not immediately clear to me what the right answer is here, and how to do extensibility seems like a good question for the WG to weigh in on.

2023-11-06 21:37 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
I propose we use `private.` and a reverse domain name label for namespacing of private events. 
MIMI  events then can use room for room events, ds for ds events, etc.

2023-11-07 07:36 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
yes

2023-11-07 07:38 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
and if we use an enum managed by IANA then we can use `room` and `dr` but the `dr` constant might be initially in the private range.

2023-11-07 14:21 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
If we use an enum instead for the IANA registry then we get the best of both worlds

2024-02-09 22:08 UTC, rohan-wire commented
Closing as this is superfluous in PR #50

2024-02-09 22:08 UTC, closed without merging