Add Basic Operations section with Alice and Bob flow.
bifurcation/ietf-mimi-protocol pull request #3
Opened 2023-10-29 16:25 UTC by rohan-wire

2023-10-29 16:31 UTC, turt2live commented
For the record: a lot of this PR's content may be different or superceded by what Konrad and I are working on in preparation for the Design Team meeting in a couple of days.

2023-10-30 20:45 UTC, turt2live requested changes
Thanks for putting this together. I do think there's value in an "Alice adds Bob then Cathy" flow, though I'm concerned that this PR goes into details not appropriate for this document (or already handled by other PRs/plans).

In the meantime, I've put some suggestions down to match editorial style more than anything. Very happy to discuss what's in and out of scope for the document at the design team meeting tomorrow.

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +HTTP semantics are not-appropriate.
```suggestion
Throughout this document, the examples use the TLS Presentation Language
{{!RFC8446}} and the semantics of HTTP {{!RFC7231}}. 

> **TODO**: Decide on binary encoding and set of transport semantics.
```

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +- Alice get the internal identifier for Bob †
This is out of scope for the design team's considerations, for now. We assume going into this document that an internal identifier has already been discovered through some means.

Later we may incorporate discovery, after the working group adopts a suitable document (or set of documents).

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +consent requirements, but there is agreement that they will exist.
I don't think we need to highlight the design team's decisions like this in the doc. For consistency, let's use the `> **TODO**: Words` syntax.

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +- Alice fetches initial keying material for Bob's clients
This is just one possible flow: Alice can also create the room and *invite* Bob to it without ever requesting key material.

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +- The hub/owning provider fans out the message
The participation changes are additionally fanned out, as is Alice's message. Which message is "the" message here?

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +## Get internal identifier for Bob
As discussed, this is out of scope for now. Let's remove it until we have an agreed working group item to work from.

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +some requirements.
```suggestion
> **TODO**: Add mechanism to achieve this. See Section 6.1 
of {{?I-D.mahy-mimi-transport-design-reqs}} for thoughts.
```

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +## Fetch initial key material for Bob
This feels overly specific for this document. It's covered by MIMI-DS, and referenced by https://github.com/bifurcation/ietf-mimi-protocol/pull/4 per the agreed document layout.

This section should be removed.

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +## Create a room
Room creation is covered elsewhere in the document. Can we add relevant detail to that instead, please?

2023-10-30 20:45 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +## Alice adds Bob
I'm not sure this needs to be a dedicated section, but much/all of the text contained within feels overly specified compared to the rest of the document. Can we merge relevant details into the other sections, please?

This comment applies to the section headers below as well.

2023-10-31 16:12 UTC, bifurcation commented on draft-ralston-mimi-protocol.md
> +- Alice fetches initial keying material for Bob's clients
Just documenting one flow seems fine for this document, for now.

2023-10-31 19:29 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +- Alice fetches initial keying material for Bob's clients
(we should at least mention that there's other possible flows though, if we still have them after our latest Alice and Bob discussions)

2023-10-31 19:30 UTC, turt2live commented
for the public record: Konrad is working on a PR which proposes an Alice adds Bob flow using the newly-decided MLS Proposal-framed signaling approach. It may be different from this PR, but should also be relatively similar.

2023-11-03 21:15 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +- Alice get the internal identifier for Bob †
Whether we address it or not, that step needs to happen, and an example flow needs to acknowledge that.

2023-11-03 21:17 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +- Alice fetches initial keying material for Bob's clients
We should document the most common flow *first* (Alice adds Bob), because with most messengers, if Alice "adds" Bob, she can send a message immediately which Bob can read after coming online (without any history passing mechanism).

2023-11-03 21:17 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +- The hub/owning provider fans out the message
good point. it could be either.

2023-11-06 11:31 UTC, kkohbrok approved these changes
We will merge this PR as is and any changes will follow as part of #14.

2023-11-06 11:31 UTC, merged