Update Introduction and add Known Gaps
bifurcation/ietf-mimi-protocol pull request #42
Opened 2024-01-29 21:10 UTC by bifurcation

The Known Gaps section might need some updating depending on what we do with the rest of the document.

2024-01-30 01:40 UTC, rohanmahy approved these changes

2024-01-30 01:40 UTC, rohanmahy commented on draft-ralston-mimi-protocol.md
> +of a protocol framework to indicate how other necessary functionality.  The
```suggestion
of a protocol framework to indicate how to add other necessary functionality.  The
```

2024-01-30 01:40 UTC, rohanmahy commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its users (who may be offline).
```suggestion
stores initial keying material and consent for its own users (who may be offline).
```

2024-01-30 15:57 UTC, kkohbrok reviewed
Thanks for the PR. Made an initial pass with a few questions and remarks.

2024-01-30 15:57 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +ordering, the participation list, and policy of its rooms. Each provider also
Is there a reason we're distinguishing between "maintains the policy and participation for the room" and then later in the sentence "and is responsible for (...) the participation list, and policy of its rooms"?

2024-01-30 15:57 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its users (who may be offline).
We should be more clear here what it means to "store consent". At least it's not clear to me.

2024-01-30 15:57 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +* Sharing room policy
What does it mean to "share room policy"? Agreement between providers? Or participants?

In any case, the other two examples seem more natural in the context of "messaging application functionality", so I'd put them first.

2024-01-30 15:57 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +identifier.  This document provides no mechanism for such resolution.
If we do want to keep a list (I think another PR removes existing remarks about missing things), we should add authentication here. We do have basic MLS authentication, but we should also be able to verify cryptographically, that a given user belongs to a given provider.

2024-01-30 17:53 UTC, rohanmahy commented on draft-ralston-mimi-protocol.md
> +ordering, the participation list, and policy of its rooms. Each provider also
I meant maintains the policy and participation as *enforcing* the policy and participation. It's also the source of truth ("responsible") for the "message ordering, the participation list, and policy of its rooms".

Feel free free to propose some alternate wording.

2024-01-30 17:54 UTC, rohanmahy commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its users (who may be offline).
if a user has granted, revoked, or rejected consent, that needs to get stored at their provider so the provider can act on behalf of the user if his or clients are offline.

2024-01-30 17:55 UTC, rohanmahy commented on draft-ralston-mimi-protocol.md
> +* Sharing room policy
I'd say "share room policy" is between participants and the hub.

2024-01-30 22:18 UTC, turt2live requested changes
Mentions of consent outside the known gaps section should be elided for now.

2024-01-30 22:18 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +The More Instant Messaging Interoperability (MIMI) protocol enables providers of
```suggestion
The More Instant Messaging Interoperability (MIMI) transport protocol enables providers of
```

2024-01-30 22:18 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its users (who may be offline).
in my opinion, we should descope consent for now. It needs a lot more thought as to how it works.

```suggestion
stores initial keying material for its own users (who may be offline).
```

2024-01-30 22:18 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +with users on other providers.
descoping consent: 
```suggestion
In support of these functions, the protocol also has primitives to fetch initial
keying material and fetch the current state of the underlying end-to-end encryption
protocol for the room.
```

2024-01-30 22:18 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +participant in the group, and that all clients in the group agree on the state
```suggestion
participant in the room, and that all clients in the group agree on the state
```

2024-01-30 22:18 UTC, turt2live commented on draft-ralston-mimi-protocol.md
> +support.
This is a bit too vague: what flows specifically are we descoping from this version?

2024-01-31 00:55 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its users (who may be offline).
This statement merely says that the providers are responsible for keeping track of the consent of their users, which should be non-controversial. This section / PR doesn't impose any specific mechanism for doing so.

2024-01-31 01:00 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +support.
Richard wanted to make a join flow easy to understand by the WG, get consensus to make it a WG item, then add other join mechanisms. So in this version I think Richard wants to start with the "member adds non-member" flow. 

I'm fine (keen even) to add a second flow where a user adds a new client or a user already on a participant list (passively) does an external join, but only if we have strong consensus from the design team. 

@turt2live are you OK with that plan of action?

2024-01-31 07:35 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its users (who may be offline).
Thanks for clarifying. I'd be okay to leave it as is for now and touch it again once we know more about how consent works.

2024-01-31 07:46 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +ordering, the participation list, and policy of its rooms. Each provider also
Something like this? 
```suggestion
become participants in the room.  The hub provider is responsible for message ordering and distribution, as well as policy enforcement. It also keeps a copy of the room state, which includes the room's policy and participant list, which it can provide to new joiners. Each provider also
```
I wouldn't say it's the "source of truth", since the truth is in the MLS group state and the MLS commits. Saying it's the source of truth (to me) implies that it has direct control over it. It stores the group state, but the group state ultimately comes from the clients (even though the hub can reject commits it doesn't like).

2024-01-31 07:54 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +* Sharing room policy
It still sounds a bit weird to me, but I don't want to nitpick too much here. Let's leave it as is for now.

2024-01-31 07:59 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
Maybe something like this?
```suggestion
Authentication
: While MLS provides basic message authentication, users should also be able to (cryptographically) tie the identity of other users to their respective providers. Further authentication such as tying clients to their users (or the user's other clients) may also be desirable.
```

2024-01-31 15:08 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +identifier.  This document provides no mechanism for such resolution.
```suggestion
identifier.  This document provides no mechanism for such resolution.

```

2024-01-31 15:20 UTC, rohan-wire commented on draft-ralston-mimi-protocol.md
> +ordering, the participation list, and policy of its rooms. Each provider also
```suggestion
become participants in the room. The hub provider is responsible for ordering
and distributing messages, enforcing policy, and authorizing messages. It also
keeps a copy of the room state, which includes the room policy and participant
list, which it can provide to new joiners. Each provider also
```

2024-02-01 06:03 UTC, kkohbrok approved these changes
Thanks for making the changes! Looks good to me now.

2024-02-01 06:05 UTC, kkohbrok commented on draft-ralston-mimi-protocol.md
> +ordering, the participation list, and policy of its rooms. Each provider also
The text looks good now, except that I don't quite get what the difference between "enforcing policy" and "authorizing messages" is. My understanding was that authorizing messages (or not) is part of policy enforcement.

2024-02-02 21:06 UTC, bifurcation commented on draft-ralston-mimi-protocol.md
> +support.
Yeah, we're descoping everything besides the basic flow from this version.  The idea here is to capture the basic moving parts for one use cases, with the idea that the WG can then elaborate them to cover other use cases after adoption.

2024-02-02 21:08 UTC, bifurcation commented on draft-ralston-mimi-protocol.md
> +stores initial keying material and consent for its own users (who may be offline).
```suggestion
stores initial keying material for its own users (who may be offline).
```

2024-02-02 21:10 UTC, merged

2024-02-06 22:43 UTC, turt2live reviewed
several days late (sorry, FOSDEM), but lgtm - thanks for applying the edits :)